import Head from "next/head";
import { Button } from "../components";

export default function Home() {
  console.log(process.env.DB_HOST);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button title="STAY GREEN" onClick={() => console.log("Hello world")} />
      </main>
      <footer>
        <p>footer</p>
      </footer>
    </div>
  );
}
